[package]
name = "orcrist-derive"
version = "0.1.0"
authors = ["Erich Gubler <erichdongubler@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
quote = "1.0.2"
syn = "1.0.11"
synstructure = "0.12.3"

[dev-dependencies]
orcrist = { path = "../orcrist" }
